with source as (

    select * from {{ source('raw', 'batting') }}

),

renamed as (

    select
        -- ids and keys
        idfg            as player_id,
        name            as player_name,
        team,
        season,
        age,
        age_rng,

        -- counting stats
        g,
        ab,
        pa,
        h,
        singles,
        doubles,
        triples,
        hr,
        r,
        rbi,
        bb,
        ibb,
        so,
        hbp,
        sf,
        sh,
        gdp,
        sb,
        cs,

        -- rate stats
        avg,
        obp,
        slg,
        ops,
        iso,
        babip,
        woba,
        bb_pct,
        k_pct,
        bb_per_k,

        -- batted ball
        gb,
        fb,
        ld,
        iffb,
        gb_pct,
        fb_pct,
        ld_pct,
        iffb_pct,
        gb_per_fb,
        hr_per_fb,
        ifh,
        ifh_pct,
        bu,
        buh,
        buh_pct,

        -- value
        war,
        l_war,
        wrc_plus,
        wrc,
        wraa,
        rar,
        bat,
        fld,
        def_runs,
        off,
        rep,
        pos,
        spd,
        bsr,
        wsb,
        ubr,
        wgdp,

        -- win probability
        wpa,
        minus_wpa,
        plus_wpa,
        wpa_per_li,
        re24,
        rew,
        pli,
        phli,
        clutch,
        lg,

        -- statcast
        ev,
        la,
        barrels,
        barrel_pct,
        maxev,
        hardhit,
        hardhit_pct,
        events,
        xba,
        xslg,
        xwoba,

        -- plate discipline
        o_swing_pct,
        z_swing_pct,
        swing_pct,
        o_contact_pct,
        z_contact_pct,
        contact_pct,
        zone_pct,
        f_strike_pct,
        swstr_pct,
        cstr_pct,
        csw_pct,
        pace,

        -- batted ball direction
        pull_pct,
        cent_pct,
        oppo_pct,
        soft_pct,
        med_pct,
        hard_pct,
        tto_pct,

        -- pitch type (simple)
        fb_pct_pitch,
        fbv,
        sl_pct,
        slv,
        ct_pct,
        ctv,
        cb_pct,
        cbv,
        ch_pct,
        chv,
        sf_pct,
        sfv,
        kn_pct,
        knv,
        xx_pct,
        po_pct,

        -- pitch values
        wfb, wsl, wct, wcb, wch, wsf, wkn,
        wfb_per_c, wsl_per_c, wct_per_c, wcb_per_c,
        wch_per_c, wsf_per_c, wkn_per_c,

        -- plus stats
        avg_plus,
        bb_pct_plus,
        k_pct_plus,
        obp_plus,
        slg_plus,
        iso_plus,
        babip_plus,
        ld_plus_pct,
        gb_pct_plus,
        fb_pct_plus,
        hr_per_fb_pct_plus,
        pull_pct_plus,
        cent_pct_plus,
        oppo_pct_plus,
        soft_pct_plus,
        med_pct_plus,
        hard_pct_plus,

        -- pitch info (sc/pi variants - keeping but grouped)
        fa_pct_sc, ft_pct_sc, fc_pct_sc, fs_pct_sc, fo_pct_sc,
        si_pct_sc, sl_pct_sc, cu_pct_sc, kc_pct_sc, ep_pct_sc,
        ch_pct_sc, sc_pct_sc, kn_pct_sc, un_pct_sc,
        vfa_sc, vft_sc, vfc_sc, vfs_sc, vfo_sc, vsi_sc, vsl_sc,
        vcu_sc, vkc_sc, vep_sc, vch_sc, vsc_sc, vkn_sc,
        fa_x_sc, ft_x_sc, fc_x_sc, fs_x_sc, fo_x_sc, si_x_sc,
        sl_x_sc, cu_x_sc, kc_x_sc, ep_x_sc, ch_x_sc, sc_x_sc, kn_x_sc,
        fa_z_sc, ft_z_sc, fc_z_sc, fs_z_sc, fo_z_sc, si_z_sc,
        sl_z_sc, cu_z_sc, kc_z_sc, ep_z_sc, ch_z_sc, sc_z_sc, kn_z_sc,
        wfa_sc, wft_sc, wfc_sc, wfs_sc, wfo_sc, wsi_sc, wsl_sc,
        wcu_sc, wkc_sc, wep_sc, wch_sc, wsc_sc, wkn_sc,
        wfa_per_c_sc, wft_per_c_sc, wfc_per_c_sc, wfs_per_c_sc,
        wfo_per_c_sc, wsi_per_c_sc, wsl_per_c_sc, wcu_per_c_sc,
        wkc_per_c_sc, wep_per_c_sc, wch_per_c_sc, wsc_per_c_sc, wkn_per_c_sc,
        o_swing_pct_sc, z_swing_pct_sc, swing_pct_sc, o_contact_pct_sc,
        z_contact_pct_sc, contact_pct_sc, zone_pct_sc,
        ch_pct_pi, cs_pct_pi, cu_pct_pi, fa_pct_pi, fc_pct_pi,
        fs_pct_pi, kn_pct_pi, sb_pct_pi, si_pct_pi, sl_pct_pi, xx_pct_pi,
        vch_pi, vcs_pi, vcu_pi, vfa_pi, vfc_pi, vfs_pi, vkn_pi,
        vsb_pi, vsi_pi, vsl_pi, vxx_pi,
        ch_x_pi, cs_x_pi, cu_x_pi, fa_x_pi, fc_x_pi, fs_x_pi,
        kn_x_pi, sb_x_pi, si_x_pi, sl_x_pi, xx_x_pi,
        ch_z_pi, cs_z_pi, cu_z_pi, fa_z_pi, fc_z_pi, fs_z_pi,
        kn_z_pi, sb_z_pi, si_z_pi, sl_z_pi, xx_z_pi,
        wch_pi, wcs_pi, wcu_pi, wfa_pi, wfc_pi, wfs_pi, wkn_pi,
        wsb_pi, wsi_pi, wsl_pi, wxx_pi,
        wch_per_c_pi, wcs_per_c_pi, wcu_per_c_pi, wfa_per_c_pi,
        wfc_per_c_pi, wfs_per_c_pi, wkn_per_c_pi, wsb_per_c_pi,
        wsi_per_c_pi, wsl_per_c_pi, wxx_per_c_pi,
        o_swing_pct_pi, z_swing_pct_pi, swing_pct_pi, o_contact_pct_pi,
        z_contact_pct_pi, contact_pct_pi, zone_pct_pi, pace_pi,
        frm,
        ph,
        pitches,
        balls,
        strikes,
        dol                     as dollar_value_estimate

    from source

)

select * from renamed
