with source as (

    select * from {{ source('raw', 'pitching') }}

),

renamed as (

    select
        -- ids and keys
        idfg            as player_id,
        name            as player_name,
        team,
        season,
        age,
        age_rng,

        -- counting stats
        w,
        l,
        g,
        gs,
        cg,
        sho,
        sv,
        bs,
        hld,
        sd,
        md,
        ip,
        start_ip,
        relief_ip,
        starting,
        relieving,
        tbf,
        h,
        r,
        er,
        hr,
        bb,
        ibb,
        hbp,
        wp,
        bk,
        so,
        rs,
        gb,
        fb,
        ld,
        iffb,
        ifh,
        bu,
        buh,
        balls,
        strikes,
        pitches,
        pulls,

        -- rate stats
        era,
        fip,
        xfip,
        siera,
        tera,
        xera,
        botera,
        whip,
        avg,
        babip,
        lob_pct,
        gb_per_fb,
        ld_pct,
        gb_pct,
        fb_pct,
        iffb_pct,
        hr_per_fb,
        ifh_pct,
        buh_pct,
        k_per_9,
        bb_per_9,
        k_per_bb,
        h_per_9,
        hr_per_9,
        rs_per_9,
        k_pct,
        bb_pct,
        k_bb_pct,
        e_f,
        kwera,

        -- scaled/park adjusted
        era_minus,
        fip_minus,
        xfip_minus,
        k_per_9_plus,
        bb_per_9_plus,
        k_per_bb_plus,
        h_per_9_plus,
        hr_per_9_plus,
        avg_plus,
        whip_plus,
        babip_plus,
        lob_pct_plus,
        k_pct_plus,
        bb_pct_plus,
        ld_pct_plus,
        gb_pct_plus,
        fb_pct_plus,
        hr_per_fb_pct_plus,
        pull_pct_plus,
        cent_pct_plus,
        oppo_pct_plus,
        soft_pct_plus,
        med_pct_plus,
        hard_pct_plus,

        -- value
        war,
        ra9_war,
        rar,
        bip_wins,
        lob_wins,
        fdp_wins,

        -- win probability
        wpa,
        minus_wpa,
        plus_wpa,
        wpa_per_li,
        re24,
        rew,
        pli,
        inli,
        gmli,
        exli,
        clutch,

        -- batted ball direction
        pull_pct,
        cent_pct,
        oppo_pct,
        soft_pct,
        med_pct,
        hard_pct,
        tto_pct,

        -- statcast
        ev,
        la,
        barrels,
        barrel_pct,
        maxev,
        hardhit,
        hardhit_pct,
        events,
        cstr_pct,
        csw_pct,
        pace,
        frm,

        -- plate discipline
        o_swing_pct,
        z_swing_pct,
        swing_pct,
        o_contact_pct,
        z_contact_pct,
        contact_pct,
        zone_pct,
        f_strike_pct,
        swstr_pct,

        -- pitch type (simple)
        fb_pct_pitch,
        fbv,
        sl_pct,
        slv,
        ct_pct,
        ctv,
        cb_pct,
        cbv,
        ch_pct,
        chv,
        sf_pct,
        sfv,
        kn_pct,
        knv,
        xx_pct,
        po_pct,

        -- pitch values
        wfb, wsl, wct, wcb, wch, wsf, wkn,
        wfb_per_c, wsl_per_c, wct_per_c, wcb_per_c,
        wch_per_c, wsf_per_c, wkn_per_c,

        -- stuff+/location+/pitching+
        stuff_plus,
        location_plus,
        pitching_plus,
        botovr,
        botstf,
        botcmd,
        botxrv100,
        stf_plus_ch, loc_plus_ch, pit_plus_ch,
        stf_plus_cu, loc_plus_cu, pit_plus_cu,
        stf_plus_fa, loc_plus_fa, pit_plus_fa,
        stf_plus_si, loc_plus_si, pit_plus_si,
        stf_plus_sl, loc_plus_sl, pit_plus_sl,
        stf_plus_kc, loc_plus_kc, pit_plus_kc,
        stf_plus_fc, loc_plus_fc, pit_plus_fc,
        stf_plus_fs, loc_plus_fs, pit_plus_fs,
        stf_plus_fo, loc_plus_fo, pit_plus_fo,
        botovr_ch, botstf_ch, botcmd_ch,
        botovr_cu, botstf_cu, botcmd_cu,
        botovr_fa, botstf_fa, botcmd_fa,
        botovr_si, botstf_si, botcmd_si,
        botovr_sl, botstf_sl, botcmd_sl,
        botovr_kc, botstf_kc, botcmd_kc,
        botovr_fc, botstf_fc, botcmd_fc,
        botovr_fs, botstf_fs, botcmd_fs,

        -- sc/pi variants
        fa_pct_sc, ft_pct_sc, fc_pct_sc, fs_pct_sc, fo_pct_sc,
        si_pct_sc, sl_pct_sc, cu_pct_sc, kc_pct_sc, ep_pct_sc,
        ch_pct_sc, sc_pct_sc, kn_pct_sc, un_pct_sc,
        vfa_sc, vft_sc, vfc_sc, vfs_sc, vfo_sc, vsi_sc, vsl_sc,
        vcu_sc, vkc_sc, vep_sc, vch_sc, vsc_sc, vkn_sc,
        fa_x_sc, ft_x_sc, fc_x_sc, fs_x_sc, fo_x_sc, si_x_sc,
        sl_x_sc, cu_x_sc, kc_x_sc, ep_x_sc, ch_x_sc, sc_x_sc, kn_x_sc,
        fa_z_sc, ft_z_sc, fc_z_sc, fs_z_sc, fo_z_sc, si_z_sc,
        sl_z_sc, cu_z_sc, kc_z_sc, ep_z_sc, ch_z_sc, sc_z_sc, kn_z_sc,
        wfa_sc, wft_sc, wfc_sc, wfs_sc, wfo_sc, wsi_sc, wsl_sc,
        wcu_sc, wkc_sc, wep_sc, wch_sc, wsc_sc, wkn_sc,
        wfa_per_c_sc, wft_per_c_sc, wfc_per_c_sc, wfs_per_c_sc,
        wfo_per_c_sc, wsi_per_c_sc, wsl_per_c_sc, wcu_per_c_sc,
        wkc_per_c_sc, wep_per_c_sc, wch_per_c_sc, wsc_per_c_sc, wkn_per_c_sc,
        o_swing_pct_sc, z_swing_pct_sc, swing_pct_sc, o_contact_pct_sc,
        z_contact_pct_sc, contact_pct_sc, zone_pct_sc,
        ch_pct_pi, cs_pct_pi, cu_pct_pi, fa_pct_pi, fc_pct_pi,
        fs_pct_pi, kn_pct_pi, sb_pct_pi, si_pct_pi, sl_pct_pi, xx_pct_pi,
        vch_pi, vcs_pi, vcu_pi, vfa_pi, vfc_pi, vfs_pi, vkn_pi,
        vsb_pi, vsi_pi, vsl_pi, vxx_pi,
        ch_x_pi, cs_x_pi, cu_x_pi, fa_x_pi, fc_x_pi, fs_x_pi,
        kn_x_pi, sb_x_pi, si_x_pi, sl_x_pi, xx_x_pi,
        ch_z_pi, cs_z_pi, cu_z_pi, fa_z_pi, fc_z_pi, fs_z_pi,
        kn_z_pi, sb_z_pi, si_z_pi, sl_z_pi, xx_z_pi,
        wch_pi, wcs_pi, wcu_pi, wfa_pi, wfc_pi, wfs_pi, wkn_pi,
        wsb_pi, wsi_pi, wsl_pi, wxx_pi,
        wch_per_c_pi, wcs_per_c_pi, wcu_per_c_pi, wfa_per_c_pi,
        wfc_per_c_pi, wfs_per_c_pi, wkn_per_c_pi, wsb_per_c_pi,
        wsi_per_c_pi, wsl_per_c_pi, wxx_per_c_pi,
        o_swing_pct_pi, z_swing_pct_pi, swing_pct_pi, o_contact_pct_pi,
        z_contact_pct_pi, contact_pct_pi, zone_pct_pi, pace_pi,

        dollars                 as dollar_value_estimate

    from source

)

select * from renamed
